import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { DogBreeds, useGetAllDogsBreedsQuery } from "../src/services/dogBreeds";
import Layout from "../components/Layout";
import Select from "../components/Select";
import {ClimbingBoxLoader} from 'react-spinners'

const Home: NextPage = () => {
  const { data, isLoading, error } = useGetAllDogsBreedsQuery();

  if (isLoading) {
    return <div className="container mx-auto flex justify-center items-center absolute inset-9">
      <ClimbingBoxLoader/>
    </div>
  }

  const dogBreeds: DogBreeds | undefined = data;
  if (dogBreeds !== undefined) {
    return (
      <div>
        <Head>
          <title>Rolex Dog Breeds App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>
          <Select dogs={dogBreeds} />
        </Layout>
      </div>
    );
  } else {
    return (<div></div>)
  }

 };

export default Home;
